/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as ContratoTokenRouteImport } from './routes/contrato.$token'
import { Route as AlunoLoginRouteImport } from './routes/aluno.login'
import { Route as AdminSetorProvasRouteImport } from './routes/_admin.setor-provas'
import { Route as AdminSegmentosRouteImport } from './routes/_admin.segmentos'
import { Route as AdminProvasAgendadasRouteImport } from './routes/_admin.provas-agendadas'
import { Route as AdminPosVendaRouteImport } from './routes/_admin.pos-venda'
import { Route as AdminPacotesRouteImport } from './routes/_admin.pacotes'
import { Route as AdminMinhasComissoesRouteImport } from './routes/_admin.minhas-comissoes'
import { Route as AdminMinhaEquipeRouteImport } from './routes/_admin.minha-equipe'
import { Route as AdminFinanceiroRouteImport } from './routes/_admin.financeiro'
import { Route as AdminConfiguracoesRouteImport } from './routes/_admin.configuracoes'
import { Route as AdminColaboradoresRouteImport } from './routes/_admin.colaboradores'
import { Route as AdminCursosIndexRouteImport } from './routes/_admin.cursos.index'
import { Route as AdminAlunosIndexRouteImport } from './routes/_admin.alunos.index'
import { Route as StudentAlunoProvaFinalRouteImport } from './routes/_student.aluno.prova-final'
import { Route as StudentAlunoPerfilRouteImport } from './routes/_student.aluno.perfil'
import { Route as StudentAlunoFinanceiroRouteImport } from './routes/_student.aluno.financeiro'
import { Route as StudentAlunoDashboardRouteImport } from './routes/_student.aluno.dashboard'
import { Route as AdminCursosNovoRouteImport } from './routes/_admin.cursos.novo'
import { Route as AdminAlunosNovoRouteImport } from './routes/_admin.alunos.novo'
import { Route as AdminAlunosIdIndexRouteImport } from './routes/_admin.alunos.$id.index'
import { Route as ApiPublicHooksZapiJobsDiariosRouteImport } from './routes/api/public/hooks/zapi-jobs-diarios'
import { Route as ApiPublicHooksWhatsappCobrancaRouteImport } from './routes/api/public/hooks/whatsapp-cobranca'
import { Route as StudentAlunoProvaFinalRealizarRouteImport } from './routes/_student.aluno.prova-final.realizar'
import { Route as StudentAlunoProvaFinalExecucaoRouteImport } from './routes/_student.aluno.prova-final.execucao'
import { Route as StudentAlunoCursoIdRouteImport } from './routes/_student.aluno.curso.$id'
import { Route as AdminCursosIdEditarRouteImport } from './routes/_admin.cursos.$id.editar'
import { Route as AdminCursosIdAulasRouteImport } from './routes/_admin.cursos.$id.aulas'
import { Route as AdminAlunosIdEditarRouteImport } from './routes/_admin.alunos.$id.editar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ContratoTokenRoute = ContratoTokenRouteImport.update({
  id: '/contrato/$token',
  path: '/contrato/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoLoginRoute = AlunoLoginRouteImport.update({
  id: '/aluno/login',
  path: '/aluno/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetorProvasRoute = AdminSetorProvasRouteImport.update({
  id: '/setor-provas',
  path: '/setor-provas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSegmentosRoute = AdminSegmentosRouteImport.update({
  id: '/segmentos',
  path: '/segmentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvasAgendadasRoute = AdminProvasAgendadasRouteImport.update({
  id: '/provas-agendadas',
  path: '/provas-agendadas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosVendaRoute = AdminPosVendaRouteImport.update({
  id: '/pos-venda',
  path: '/pos-venda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPacotesRoute = AdminPacotesRouteImport.update({
  id: '/pacotes',
  path: '/pacotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMinhasComissoesRoute = AdminMinhasComissoesRouteImport.update({
  id: '/minhas-comissoes',
  path: '/minhas-comissoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMinhaEquipeRoute = AdminMinhaEquipeRouteImport.update({
  id: '/minha-equipe',
  path: '/minha-equipe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminColaboradoresRoute = AdminColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCursosIndexRoute = AdminCursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosIndexRoute = AdminAlunosIndexRouteImport.update({
  id: '/alunos/',
  path: '/alunos/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentAlunoProvaFinalRoute = StudentAlunoProvaFinalRouteImport.update({
  id: '/aluno/prova-final',
  path: '/aluno/prova-final',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAlunoPerfilRoute = StudentAlunoPerfilRouteImport.update({
  id: '/aluno/perfil',
  path: '/aluno/perfil',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAlunoFinanceiroRoute = StudentAlunoFinanceiroRouteImport.update({
  id: '/aluno/financeiro',
  path: '/aluno/financeiro',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAlunoDashboardRoute = StudentAlunoDashboardRouteImport.update({
  id: '/aluno/dashboard',
  path: '/aluno/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const AdminCursosNovoRoute = AdminCursosNovoRouteImport.update({
  id: '/cursos/novo',
  path: '/cursos/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosNovoRoute = AdminAlunosNovoRouteImport.update({
  id: '/alunos/novo',
  path: '/alunos/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosIdIndexRoute = AdminAlunosIdIndexRouteImport.update({
  id: '/alunos/$id/',
  path: '/alunos/$id/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksZapiJobsDiariosRoute =
  ApiPublicHooksZapiJobsDiariosRouteImport.update({
    id: '/api/public/hooks/zapi-jobs-diarios',
    path: '/api/public/hooks/zapi-jobs-diarios',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWhatsappCobrancaRoute =
  ApiPublicHooksWhatsappCobrancaRouteImport.update({
    id: '/api/public/hooks/whatsapp-cobranca',
    path: '/api/public/hooks/whatsapp-cobranca',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentAlunoProvaFinalRealizarRoute =
  StudentAlunoProvaFinalRealizarRouteImport.update({
    id: '/realizar',
    path: '/realizar',
    getParentRoute: () => StudentAlunoProvaFinalRoute,
  } as any)
const StudentAlunoProvaFinalExecucaoRoute =
  StudentAlunoProvaFinalExecucaoRouteImport.update({
    id: '/execucao',
    path: '/execucao',
    getParentRoute: () => StudentAlunoProvaFinalRoute,
  } as any)
const StudentAlunoCursoIdRoute = StudentAlunoCursoIdRouteImport.update({
  id: '/aluno/curso/$id',
  path: '/aluno/curso/$id',
  getParentRoute: () => StudentRoute,
} as any)
const AdminCursosIdEditarRoute = AdminCursosIdEditarRouteImport.update({
  id: '/cursos/$id/editar',
  path: '/cursos/$id/editar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCursosIdAulasRoute = AdminCursosIdAulasRouteImport.update({
  id: '/cursos/$id/aulas',
  path: '/cursos/$id/aulas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosIdEditarRoute = AdminAlunosIdEditarRouteImport.update({
  id: '/alunos/$id/editar',
  path: '/alunos/$id/editar',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/colaboradores': typeof AdminColaboradoresRoute
  '/configuracoes': typeof AdminConfiguracoesRoute
  '/financeiro': typeof AdminFinanceiroRoute
  '/minha-equipe': typeof AdminMinhaEquipeRoute
  '/minhas-comissoes': typeof AdminMinhasComissoesRoute
  '/pacotes': typeof AdminPacotesRoute
  '/pos-venda': typeof AdminPosVendaRoute
  '/provas-agendadas': typeof AdminProvasAgendadasRoute
  '/segmentos': typeof AdminSegmentosRoute
  '/setor-provas': typeof AdminSetorProvasRoute
  '/aluno/login': typeof AlunoLoginRoute
  '/contrato/$token': typeof ContratoTokenRoute
  '/alunos/novo': typeof AdminAlunosNovoRoute
  '/cursos/novo': typeof AdminCursosNovoRoute
  '/aluno/dashboard': typeof StudentAlunoDashboardRoute
  '/aluno/financeiro': typeof StudentAlunoFinanceiroRoute
  '/aluno/perfil': typeof StudentAlunoPerfilRoute
  '/aluno/prova-final': typeof StudentAlunoProvaFinalRouteWithChildren
  '/alunos/': typeof AdminAlunosIndexRoute
  '/cursos/': typeof AdminCursosIndexRoute
  '/alunos/$id/editar': typeof AdminAlunosIdEditarRoute
  '/cursos/$id/aulas': typeof AdminCursosIdAulasRoute
  '/cursos/$id/editar': typeof AdminCursosIdEditarRoute
  '/aluno/curso/$id': typeof StudentAlunoCursoIdRoute
  '/aluno/prova-final/execucao': typeof StudentAlunoProvaFinalExecucaoRoute
  '/aluno/prova-final/realizar': typeof StudentAlunoProvaFinalRealizarRoute
  '/api/public/hooks/whatsapp-cobranca': typeof ApiPublicHooksWhatsappCobrancaRoute
  '/api/public/hooks/zapi-jobs-diarios': typeof ApiPublicHooksZapiJobsDiariosRoute
  '/alunos/$id/': typeof AdminAlunosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/colaboradores': typeof AdminColaboradoresRoute
  '/configuracoes': typeof AdminConfiguracoesRoute
  '/financeiro': typeof AdminFinanceiroRoute
  '/minha-equipe': typeof AdminMinhaEquipeRoute
  '/minhas-comissoes': typeof AdminMinhasComissoesRoute
  '/pacotes': typeof AdminPacotesRoute
  '/pos-venda': typeof AdminPosVendaRoute
  '/provas-agendadas': typeof AdminProvasAgendadasRoute
  '/segmentos': typeof AdminSegmentosRoute
  '/setor-provas': typeof AdminSetorProvasRoute
  '/aluno/login': typeof AlunoLoginRoute
  '/contrato/$token': typeof ContratoTokenRoute
  '/alunos/novo': typeof AdminAlunosNovoRoute
  '/cursos/novo': typeof AdminCursosNovoRoute
  '/aluno/dashboard': typeof StudentAlunoDashboardRoute
  '/aluno/financeiro': typeof StudentAlunoFinanceiroRoute
  '/aluno/perfil': typeof StudentAlunoPerfilRoute
  '/aluno/prova-final': typeof StudentAlunoProvaFinalRouteWithChildren
  '/alunos': typeof AdminAlunosIndexRoute
  '/cursos': typeof AdminCursosIndexRoute
  '/alunos/$id/editar': typeof AdminAlunosIdEditarRoute
  '/cursos/$id/aulas': typeof AdminCursosIdAulasRoute
  '/cursos/$id/editar': typeof AdminCursosIdEditarRoute
  '/aluno/curso/$id': typeof StudentAlunoCursoIdRoute
  '/aluno/prova-final/execucao': typeof StudentAlunoProvaFinalExecucaoRoute
  '/aluno/prova-final/realizar': typeof StudentAlunoProvaFinalRealizarRoute
  '/api/public/hooks/whatsapp-cobranca': typeof ApiPublicHooksWhatsappCobrancaRoute
  '/api/public/hooks/zapi-jobs-diarios': typeof ApiPublicHooksZapiJobsDiariosRoute
  '/alunos/$id': typeof AdminAlunosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/colaboradores': typeof AdminColaboradoresRoute
  '/_admin/configuracoes': typeof AdminConfiguracoesRoute
  '/_admin/financeiro': typeof AdminFinanceiroRoute
  '/_admin/minha-equipe': typeof AdminMinhaEquipeRoute
  '/_admin/minhas-comissoes': typeof AdminMinhasComissoesRoute
  '/_admin/pacotes': typeof AdminPacotesRoute
  '/_admin/pos-venda': typeof AdminPosVendaRoute
  '/_admin/provas-agendadas': typeof AdminProvasAgendadasRoute
  '/_admin/segmentos': typeof AdminSegmentosRoute
  '/_admin/setor-provas': typeof AdminSetorProvasRoute
  '/aluno/login': typeof AlunoLoginRoute
  '/contrato/$token': typeof ContratoTokenRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/alunos/novo': typeof AdminAlunosNovoRoute
  '/_admin/cursos/novo': typeof AdminCursosNovoRoute
  '/_student/aluno/dashboard': typeof StudentAlunoDashboardRoute
  '/_student/aluno/financeiro': typeof StudentAlunoFinanceiroRoute
  '/_student/aluno/perfil': typeof StudentAlunoPerfilRoute
  '/_student/aluno/prova-final': typeof StudentAlunoProvaFinalRouteWithChildren
  '/_admin/alunos/': typeof AdminAlunosIndexRoute
  '/_admin/cursos/': typeof AdminCursosIndexRoute
  '/_admin/alunos/$id/editar': typeof AdminAlunosIdEditarRoute
  '/_admin/cursos/$id/aulas': typeof AdminCursosIdAulasRoute
  '/_admin/cursos/$id/editar': typeof AdminCursosIdEditarRoute
  '/_student/aluno/curso/$id': typeof StudentAlunoCursoIdRoute
  '/_student/aluno/prova-final/execucao': typeof StudentAlunoProvaFinalExecucaoRoute
  '/_student/aluno/prova-final/realizar': typeof StudentAlunoProvaFinalRealizarRoute
  '/api/public/hooks/whatsapp-cobranca': typeof ApiPublicHooksWhatsappCobrancaRoute
  '/api/public/hooks/zapi-jobs-diarios': typeof ApiPublicHooksZapiJobsDiariosRoute
  '/_admin/alunos/$id/': typeof AdminAlunosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/colaboradores'
    | '/configuracoes'
    | '/financeiro'
    | '/minha-equipe'
    | '/minhas-comissoes'
    | '/pacotes'
    | '/pos-venda'
    | '/provas-agendadas'
    | '/segmentos'
    | '/setor-provas'
    | '/aluno/login'
    | '/contrato/$token'
    | '/alunos/novo'
    | '/cursos/novo'
    | '/aluno/dashboard'
    | '/aluno/financeiro'
    | '/aluno/perfil'
    | '/aluno/prova-final'
    | '/alunos/'
    | '/cursos/'
    | '/alunos/$id/editar'
    | '/cursos/$id/aulas'
    | '/cursos/$id/editar'
    | '/aluno/curso/$id'
    | '/aluno/prova-final/execucao'
    | '/aluno/prova-final/realizar'
    | '/api/public/hooks/whatsapp-cobranca'
    | '/api/public/hooks/zapi-jobs-diarios'
    | '/alunos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/colaboradores'
    | '/configuracoes'
    | '/financeiro'
    | '/minha-equipe'
    | '/minhas-comissoes'
    | '/pacotes'
    | '/pos-venda'
    | '/provas-agendadas'
    | '/segmentos'
    | '/setor-provas'
    | '/aluno/login'
    | '/contrato/$token'
    | '/alunos/novo'
    | '/cursos/novo'
    | '/aluno/dashboard'
    | '/aluno/financeiro'
    | '/aluno/perfil'
    | '/aluno/prova-final'
    | '/alunos'
    | '/cursos'
    | '/alunos/$id/editar'
    | '/cursos/$id/aulas'
    | '/cursos/$id/editar'
    | '/aluno/curso/$id'
    | '/aluno/prova-final/execucao'
    | '/aluno/prova-final/realizar'
    | '/api/public/hooks/whatsapp-cobranca'
    | '/api/public/hooks/zapi-jobs-diarios'
    | '/alunos/$id'
  id:
    | '__root__'
    | '/_admin'
    | '/_student'
    | '/login'
    | '/_admin/colaboradores'
    | '/_admin/configuracoes'
    | '/_admin/financeiro'
    | '/_admin/minha-equipe'
    | '/_admin/minhas-comissoes'
    | '/_admin/pacotes'
    | '/_admin/pos-venda'
    | '/_admin/provas-agendadas'
    | '/_admin/segmentos'
    | '/_admin/setor-provas'
    | '/aluno/login'
    | '/contrato/$token'
    | '/_admin/'
    | '/_admin/alunos/novo'
    | '/_admin/cursos/novo'
    | '/_student/aluno/dashboard'
    | '/_student/aluno/financeiro'
    | '/_student/aluno/perfil'
    | '/_student/aluno/prova-final'
    | '/_admin/alunos/'
    | '/_admin/cursos/'
    | '/_admin/alunos/$id/editar'
    | '/_admin/cursos/$id/aulas'
    | '/_admin/cursos/$id/editar'
    | '/_student/aluno/curso/$id'
    | '/_student/aluno/prova-final/execucao'
    | '/_student/aluno/prova-final/realizar'
    | '/api/public/hooks/whatsapp-cobranca'
    | '/api/public/hooks/zapi-jobs-diarios'
    | '/_admin/alunos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  LoginRoute: typeof LoginRoute
  AlunoLoginRoute: typeof AlunoLoginRoute
  ContratoTokenRoute: typeof ContratoTokenRoute
  ApiPublicHooksWhatsappCobrancaRoute: typeof ApiPublicHooksWhatsappCobrancaRoute
  ApiPublicHooksZapiJobsDiariosRoute: typeof ApiPublicHooksZapiJobsDiariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/contrato/$token': {
      id: '/contrato/$token'
      path: '/contrato/$token'
      fullPath: '/contrato/$token'
      preLoaderRoute: typeof ContratoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/login': {
      id: '/aluno/login'
      path: '/aluno/login'
      fullPath: '/aluno/login'
      preLoaderRoute: typeof AlunoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/setor-provas': {
      id: '/_admin/setor-provas'
      path: '/setor-provas'
      fullPath: '/setor-provas'
      preLoaderRoute: typeof AdminSetorProvasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/segmentos': {
      id: '/_admin/segmentos'
      path: '/segmentos'
      fullPath: '/segmentos'
      preLoaderRoute: typeof AdminSegmentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/provas-agendadas': {
      id: '/_admin/provas-agendadas'
      path: '/provas-agendadas'
      fullPath: '/provas-agendadas'
      preLoaderRoute: typeof AdminProvasAgendadasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/pos-venda': {
      id: '/_admin/pos-venda'
      path: '/pos-venda'
      fullPath: '/pos-venda'
      preLoaderRoute: typeof AdminPosVendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/pacotes': {
      id: '/_admin/pacotes'
      path: '/pacotes'
      fullPath: '/pacotes'
      preLoaderRoute: typeof AdminPacotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/minhas-comissoes': {
      id: '/_admin/minhas-comissoes'
      path: '/minhas-comissoes'
      fullPath: '/minhas-comissoes'
      preLoaderRoute: typeof AdminMinhasComissoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/minha-equipe': {
      id: '/_admin/minha-equipe'
      path: '/minha-equipe'
      fullPath: '/minha-equipe'
      preLoaderRoute: typeof AdminMinhaEquipeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/financeiro': {
      id: '/_admin/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/configuracoes': {
      id: '/_admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/colaboradores': {
      id: '/_admin/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AdminColaboradoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cursos/': {
      id: '/_admin/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof AdminCursosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/alunos/': {
      id: '/_admin/alunos/'
      path: '/alunos'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AdminAlunosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_student/aluno/prova-final': {
      id: '/_student/aluno/prova-final'
      path: '/aluno/prova-final'
      fullPath: '/aluno/prova-final'
      preLoaderRoute: typeof StudentAlunoProvaFinalRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/aluno/perfil': {
      id: '/_student/aluno/perfil'
      path: '/aluno/perfil'
      fullPath: '/aluno/perfil'
      preLoaderRoute: typeof StudentAlunoPerfilRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/aluno/financeiro': {
      id: '/_student/aluno/financeiro'
      path: '/aluno/financeiro'
      fullPath: '/aluno/financeiro'
      preLoaderRoute: typeof StudentAlunoFinanceiroRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/aluno/dashboard': {
      id: '/_student/aluno/dashboard'
      path: '/aluno/dashboard'
      fullPath: '/aluno/dashboard'
      preLoaderRoute: typeof StudentAlunoDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_admin/cursos/novo': {
      id: '/_admin/cursos/novo'
      path: '/cursos/novo'
      fullPath: '/cursos/novo'
      preLoaderRoute: typeof AdminCursosNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/alunos/novo': {
      id: '/_admin/alunos/novo'
      path: '/alunos/novo'
      fullPath: '/alunos/novo'
      preLoaderRoute: typeof AdminAlunosNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/alunos/$id/': {
      id: '/_admin/alunos/$id/'
      path: '/alunos/$id'
      fullPath: '/alunos/$id/'
      preLoaderRoute: typeof AdminAlunosIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/zapi-jobs-diarios': {
      id: '/api/public/hooks/zapi-jobs-diarios'
      path: '/api/public/hooks/zapi-jobs-diarios'
      fullPath: '/api/public/hooks/zapi-jobs-diarios'
      preLoaderRoute: typeof ApiPublicHooksZapiJobsDiariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp-cobranca': {
      id: '/api/public/hooks/whatsapp-cobranca'
      path: '/api/public/hooks/whatsapp-cobranca'
      fullPath: '/api/public/hooks/whatsapp-cobranca'
      preLoaderRoute: typeof ApiPublicHooksWhatsappCobrancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/aluno/prova-final/realizar': {
      id: '/_student/aluno/prova-final/realizar'
      path: '/realizar'
      fullPath: '/aluno/prova-final/realizar'
      preLoaderRoute: typeof StudentAlunoProvaFinalRealizarRouteImport
      parentRoute: typeof StudentAlunoProvaFinalRoute
    }
    '/_student/aluno/prova-final/execucao': {
      id: '/_student/aluno/prova-final/execucao'
      path: '/execucao'
      fullPath: '/aluno/prova-final/execucao'
      preLoaderRoute: typeof StudentAlunoProvaFinalExecucaoRouteImport
      parentRoute: typeof StudentAlunoProvaFinalRoute
    }
    '/_student/aluno/curso/$id': {
      id: '/_student/aluno/curso/$id'
      path: '/aluno/curso/$id'
      fullPath: '/aluno/curso/$id'
      preLoaderRoute: typeof StudentAlunoCursoIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_admin/cursos/$id/editar': {
      id: '/_admin/cursos/$id/editar'
      path: '/cursos/$id/editar'
      fullPath: '/cursos/$id/editar'
      preLoaderRoute: typeof AdminCursosIdEditarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cursos/$id/aulas': {
      id: '/_admin/cursos/$id/aulas'
      path: '/cursos/$id/aulas'
      fullPath: '/cursos/$id/aulas'
      preLoaderRoute: typeof AdminCursosIdAulasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/alunos/$id/editar': {
      id: '/_admin/alunos/$id/editar'
      path: '/alunos/$id/editar'
      fullPath: '/alunos/$id/editar'
      preLoaderRoute: typeof AdminAlunosIdEditarRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminColaboradoresRoute: typeof AdminColaboradoresRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminMinhaEquipeRoute: typeof AdminMinhaEquipeRoute
  AdminMinhasComissoesRoute: typeof AdminMinhasComissoesRoute
  AdminPacotesRoute: typeof AdminPacotesRoute
  AdminPosVendaRoute: typeof AdminPosVendaRoute
  AdminProvasAgendadasRoute: typeof AdminProvasAgendadasRoute
  AdminSegmentosRoute: typeof AdminSegmentosRoute
  AdminSetorProvasRoute: typeof AdminSetorProvasRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAlunosNovoRoute: typeof AdminAlunosNovoRoute
  AdminCursosNovoRoute: typeof AdminCursosNovoRoute
  AdminAlunosIndexRoute: typeof AdminAlunosIndexRoute
  AdminCursosIndexRoute: typeof AdminCursosIndexRoute
  AdminAlunosIdEditarRoute: typeof AdminAlunosIdEditarRoute
  AdminCursosIdAulasRoute: typeof AdminCursosIdAulasRoute
  AdminCursosIdEditarRoute: typeof AdminCursosIdEditarRoute
  AdminAlunosIdIndexRoute: typeof AdminAlunosIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminColaboradoresRoute: AdminColaboradoresRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminMinhaEquipeRoute: AdminMinhaEquipeRoute,
  AdminMinhasComissoesRoute: AdminMinhasComissoesRoute,
  AdminPacotesRoute: AdminPacotesRoute,
  AdminPosVendaRoute: AdminPosVendaRoute,
  AdminProvasAgendadasRoute: AdminProvasAgendadasRoute,
  AdminSegmentosRoute: AdminSegmentosRoute,
  AdminSetorProvasRoute: AdminSetorProvasRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAlunosNovoRoute: AdminAlunosNovoRoute,
  AdminCursosNovoRoute: AdminCursosNovoRoute,
  AdminAlunosIndexRoute: AdminAlunosIndexRoute,
  AdminCursosIndexRoute: AdminCursosIndexRoute,
  AdminAlunosIdEditarRoute: AdminAlunosIdEditarRoute,
  AdminCursosIdAulasRoute: AdminCursosIdAulasRoute,
  AdminCursosIdEditarRoute: AdminCursosIdEditarRoute,
  AdminAlunosIdIndexRoute: AdminAlunosIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentAlunoProvaFinalRouteChildren {
  StudentAlunoProvaFinalExecucaoRoute: typeof StudentAlunoProvaFinalExecucaoRoute
  StudentAlunoProvaFinalRealizarRoute: typeof StudentAlunoProvaFinalRealizarRoute
}

const StudentAlunoProvaFinalRouteChildren: StudentAlunoProvaFinalRouteChildren =
  {
    StudentAlunoProvaFinalExecucaoRoute: StudentAlunoProvaFinalExecucaoRoute,
    StudentAlunoProvaFinalRealizarRoute: StudentAlunoProvaFinalRealizarRoute,
  }

const StudentAlunoProvaFinalRouteWithChildren =
  StudentAlunoProvaFinalRoute._addFileChildren(
    StudentAlunoProvaFinalRouteChildren,
  )

interface StudentRouteChildren {
  StudentAlunoDashboardRoute: typeof StudentAlunoDashboardRoute
  StudentAlunoFinanceiroRoute: typeof StudentAlunoFinanceiroRoute
  StudentAlunoPerfilRoute: typeof StudentAlunoPerfilRoute
  StudentAlunoProvaFinalRoute: typeof StudentAlunoProvaFinalRouteWithChildren
  StudentAlunoCursoIdRoute: typeof StudentAlunoCursoIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAlunoDashboardRoute: StudentAlunoDashboardRoute,
  StudentAlunoFinanceiroRoute: StudentAlunoFinanceiroRoute,
  StudentAlunoPerfilRoute: StudentAlunoPerfilRoute,
  StudentAlunoProvaFinalRoute: StudentAlunoProvaFinalRouteWithChildren,
  StudentAlunoCursoIdRoute: StudentAlunoCursoIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  LoginRoute: LoginRoute,
  AlunoLoginRoute: AlunoLoginRoute,
  ContratoTokenRoute: ContratoTokenRoute,
  ApiPublicHooksWhatsappCobrancaRoute: ApiPublicHooksWhatsappCobrancaRoute,
  ApiPublicHooksZapiJobsDiariosRoute: ApiPublicHooksZapiJobsDiariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
